# Generated by Django 3.1 on 2020-08-16 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200816_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='favourite_genres',
            field=models.CharField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='movie',
        ),
    ]
